ci: better debug now?

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -268,12 +268,9 @@ jobs:
         run: |
           # DEBUG
           if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
-            # echo "trying to look into the pantry"
-            # ls -la '${{ env.STACK_ROOT }}\pantry' || echo "list pantry failed"
-            # ls -la '${{ env.STACK_ROOT }}\pantry\hackage\' || echo "list pantry\hackage failed"
             which ghc || echo "which ghc failed"
             ls -la '${{ env.GHCUP_PATH_WINDOWS }}\bin' || echo "list ghcup/bin failed"
-            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\ghc\${{ env.GHC_VERSION }}.*\lib" || echo "list ghcup\ghc\lib failed"
+            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\ghc\${{ env.GHC_VERSION }}.8\lib" || echo "list ghcup\ghc\lib failed"
             echo 'PATH'
             echo "$PATH"
             echo
