ci: and AGAIN

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -270,7 +270,7 @@ jobs:
             # ls -la '${{ env.STACK_ROOT }}\pantry\hackage\' || echo "list pantry\hackage failed"
             which ghc || echo "which ghc failed"
             ls -la '${{ env.GHCUP_PATH_WINDOWS }}\bin' || echo "list ghcup/bin failed"
-            ls -la '${{ env.GHCUP_PATH_WINDOWS }}\${{ env.GHC_VERSION }}.*\lib' || echo "list ghcup\ghc\lib failed"
+            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\${{ env.GHC_VERSION }}.*\lib" || echo "list ghcup\ghc\lib failed"
             echo 'PATH'
             echo "$PATH"
             echo
