ci: just try to get the binaries

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -27,12 +27,12 @@ jobs:
         os: ["macos-latest"]
         stack: ["latest"]
         resolver:
-          - "nightly" # 9.12
-          - "lts-24" #  9.10
-          - "lts-23" #  9.8
-          - "lts-22" #  9.6
+          # - "nightly" # 9.12
+          # - "lts-24" #  9.10
+          # - "lts-23" #  9.8
+          # - "lts-22" #  9.6
           - "lts-21" #  9.4
-          - "lts-20" #  9.2
+          # - "lts-20" #  9.2
 
     steps:
       - name: "Set ENV vars per LTS"
@@ -126,6 +126,9 @@ jobs:
         if: matrix.os == 'macos-latest' && steps.ghcup-cache-unix.outputs.cache-hit != 'true'
         run: |
           echo "$PATH"
+          which ghcup || echo '"which ghcup" failed'
+          ls -la "$HOME/.ghcup/bin" || echo '"list .ghcup" failed'
+          find "$HOME" -iname ghcup || echo '"find ghcup" failed'
           ghcup whereis stack || {
             echo '"ghcup whereis" failed'
             exit 1
