ci: just copy the stack exe

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -126,15 +126,13 @@ jobs:
         if: matrix.os == 'macos-latest' && steps.ghcup-cache-unix.outputs.cache-hit != 'true'
         run: |
           # DEBUGGING PURPOSES
-          echo "GHCup exe: ${{ steps.ghcup-install.outputs.ghc-exe }}"
-          echo "Stack exe: ${{ steps.ghcup-install.outputs.stack-exe }}"
+          # echo "Stack exe: ${{ steps.ghcup-install.outputs.stack-exe }}"
 
-          echo "$PATH"
-          ls -la "$HOME/.ghcup/bin" || echo '"list .ghcup" failed'
-          find "$HOME" -iname ghcup || echo '"find ghcup" failed'
+          # echo "$PATH"
+          # ls -la "$HOME/.ghcup/bin" || echo '"list .ghcup" failed'
+          # find "$HOME" -iname ghcup || echo '"find ghcup" failed'
           # DEBUGGING PURPOSES
 
-          cp "${{ steps.ghcup-install.outputs.ghc-exe }}" "$HOME/.ghcup/bin"
           cp "${{ steps.ghcup-install.outputs.stack-exe }}" "$HOME/.ghcup/bin"
 
       - name: Cache Pantry (Stackage package index) Unix
