ci: try to copy stack executable

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -127,8 +127,11 @@ jobs:
         id: stack-copy-macos
         if: matrix.os == 'macos-latest' && steps.ghcup-cache-unix.outputs.cache-hit != 'true'
         run: |
-          export PATH="${{ env.GHCUP_PATH_UNIX }}/bin:$PATH"
-          ghcup whereis stack || { echo "ghcup whereis failed"; exit 1 }
+          export PATH="$HOME/.ghcup/bin:$PATH"
+          ghcup whereis stack || {
+            echo "ghcup whereis failed"
+            exit 1
+          }
           STACKFILE=$(ghcup whereis stack)
           cp "$STACKFILE" "${{ env.GHCUP_PATH_UNIX }}/bin/stack"
 
