ci: check that the VARs are still correct

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,20 +16,6 @@ jobs:
     env:
       MANUAL_RESET: "v8"
       STACK_PATH_LOCAL: ".stack-work"
-      # If you want to cache local files, try this list:
-      # STACK_PATH_LOCAL: |
-      #   .stack-work/stack.sqlite3
-      #   **/.stack-work/**/*.a
-      #   **/.stack-work/**/*.cache
-      #   **/.stack-work/**/*.conf
-      #   **/.stack-work/**/*.dyn_hi
-      #   **/.stack-work/**/*.dyn_o
-      #   **/.stack-work/**/*.h
-      #   **/.stack-work/**/*.hi
-      #   **/.stack-work/**/*.hs
-      #   **/.stack-work/**/*.so
-      GHCUP_PATH_WINDOWS: 'C:\ghcup'
-      GHCUP_PATH_UNIX: "~/.ghcup"
 
     strategy:
       fail-fast: false
@@ -82,18 +68,19 @@ jobs:
 
           if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
             STACK_ROOT='C:\sr'
-            # Avoiding weird escape sequence (\$) interaction
-            GHCUP_GHC_PATH_TEMP='${{ env.GHCUP_PATH_WINDOWS }}\ghc\'
-            GHCUP_GHC_PATH="${GHCUP_GHC_PATH_TEMP}${GHC_VERSION}.*"
+            GHCUP_PATH='C:\ghcup'
+            GHCUP_GHC_PATH="${GHCUP_PATH}\\ghc\\${GHC_VERSION}.*"
           else
             STACK_ROOT="$HOME/.stack"
-            GHCUP_GHC_PATH="${{ env.GHCUP_PATH_UNIX }}/ghc/${GHC_VERSION}.*"
+            GHCUP_PATH="~/.ghcup"
+            GHCUP_GHC_PATH="${GHCUP_PATH}/ghc/${GHC_VERSION}.*"
           fi
 
           # And then we expose these variables in the 'env'
           echo "STACKYAML=$STACKYAML" >> $GITHUB_ENV
           echo "STACKYAMLLOCK=${STACKYAML}.lock" >> $GITHUB_ENV
           echo "GHC_VERSION=$GHC_VERSION" >> $GITHUB_ENV
+          echo "GHCUP_PATH=$GHCUP_PATH" >> $GITHUB_ENV
           echo "GHCUP_GHC_PATH=$GHCUP_GHC_PATH" >> $GITHUB_ENV
           echo "STACK_ROOT=$STACK_ROOT" >> $GITHUB_ENV
 
@@ -110,19 +97,19 @@ jobs:
         id: ghcup-cache-unix
         with:
           path: |
-            ${{ env.GHCUP_PATH_UNIX }}/bin/*
-            ${{ env.GHCUP_PATH_UNIX }}/cabal/*
-            ${{ env.GHCUP_PATH_UNIX }}/config.yaml
-            ${{ env.GHCUP_PATH_UNIX }}/stack/*
+            ${{ env.GHCUP_PATH }}/bin/*
+            ${{ env.GHCUP_PATH }}/cabal/*
+            ${{ env.GHCUP_PATH }}/config.yaml
+            ${{ env.GHCUP_PATH }}/stack/*
             ${{ env.GHCUP_GHC_PATH }}/bin
             ${{ env.GHCUP_GHC_PATH }}/lib
             #     [EXCLUDES]
             # We don't need GHCup to run stack, so don't cache it
-            !${{ env.GHCUP_PATH_UNIX }}/bin/ghcup
+            !${{ env.GHCUP_PATH }}/bin/ghcup
             # We don't need profile builds of GHC etc
             !${{ env.GHCUP_GHC_PATH }}/lib/ghc-${{ env.GHC_VERSION }}.*/bin/ghc-iserv*
             # Takes up lots of space, not sure if needed
-            !${{ env.GHCUP_PATH_UNIX }}/ghc/${{ env.GHC_VERSION }}.*/**/*.a
+            !${{ env.GHCUP_PATH }}/ghc/${{ env.GHC_VERSION }}.*/**/*.a
           key: CI-test9-ghcup-unix-${{ env.MANUAL_RESET }}-${{ matrix.os }}-${{ env.GHC_VERSION }}
           # restore-keys: |
           #   CI-ghcup-unix-${{ env.MANUAL_RESET }}-${{ matrix.os }}-
@@ -133,15 +120,15 @@ jobs:
         id: ghcup-cache-windows
         with:
           path: |
-            ${{ env.GHCUP_PATH_WINDOWS }}\bin
-            ${{ env.GHCUP_PATH_WINDOWS }}\cabal\*
-            ${{ env.GHCUP_PATH_WINDOWS }}\config.yaml
-            ${{ env.GHCUP_PATH_WINDOWS }}\stack\*
+            ${{ env.GHCUP_PATH }}\bin
+            ${{ env.GHCUP_PATH }}\cabal\*
+            ${{ env.GHCUP_PATH }}\config.yaml
+            ${{ env.GHCUP_PATH }}\stack\*
             ${{ env.GHCUP_GHC_PATH }}\bin\*
             ${{ env.GHCUP_GHC_PATH }}\lib\*
             #     [EXCLUDES]
             # We don't need GHCup to run stack, so don't cache it
-            !${{ env.GHCUP_PATH_WINDOWS }}\bin\ghcup.exe
+            !${{ env.GHCUP_PATH }}\bin\ghcup.exe
           key: CI-test10-ghcup-windows-${{ env.MANUAL_RESET }}-${{ env.GHC_VERSION }}
           # restore-keys: |
           #   CI-ghcup-windows-${{ env.MANUAL_RESET }}-
@@ -278,12 +265,12 @@ jobs:
             which ghc || echo "which ghc failed"
             ls -la 'C:\tools' || echo "list tools failed"
             ls -la 'C:\tools\ghc*' || echo "list tools/ghc failed"
-            ls -la '${{ env.GHCUP_PATH_WINDOWS }}' || echo "list ghcup failed"
-            ls -la '${{ env.GHCUP_PATH_WINDOWS }}\bin' || echo "list ghcup/bin failed"
-            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\ghc" || echo "list ghcup\ghc failed"
-            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\ghc\${{ env.GHC_VERSION }}.8" || echo "list ghcup\ghc\9.4.8 failed"
-            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\ghc\${{ env.GHC_VERSION }}.8\lib" || echo "list ghcup\ghc\lib failed"
-            ls -la "${{ env.GHCUP_PATH_WINDOWS }}\ghc\${{ env.GHC_VERSION }}.8\lib\bin" || echo "list ghcup\ghc\lib\bin failed"
+            ls -la '${{ env.GHCUP_PATH }}' || echo "list ghcup failed"
+            ls -la '${{ env.GHCUP_PATH }}\bin' || echo "list ghcup/bin failed"
+            ls -la "${{ env.GHCUP_PATH }}\ghc" || echo "list ghcup\ghc failed"
+            ls -la "${{ env.GHCUP_PATH }}\ghc\${{ env.GHC_VERSION }}.8" || echo "list ghcup\ghc\9.4.8 failed"
+            ls -la "${{ env.GHCUP_PATH }}\ghc\${{ env.GHC_VERSION }}.8\lib" || echo "list ghcup\ghc\lib failed"
+            ls -la "${{ env.GHCUP_PATH }}\ghc\${{ env.GHC_VERSION }}.8\lib\bin" || echo "list ghcup\ghc\lib\bin failed"
             echo
           fi
 
