ci: let's find out why GHCup doesn't add to PATH on mac... sometimes

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -199,7 +199,9 @@ jobs:
           if [[ "${{ matrix.os == 'macos-latest' }}" ]]; then
             echo $PATH
             export PATH="${{ env.GHCUP_PATH_UNIX }}/bin:$PATH"
-            which stack
+            echo $PATH
+            which stack || echo "which failed"
+            find . -iname stack || echo "find failed"
             stack --version
           fi
           stack config set system-ghc true --global
